basePath: /
definitions:
  api.Task:
    properties:
      completed:
        type: boolean
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  api.TaskInput:
    properties:
      completed:
        type: boolean
      description:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing tasks
  title: Task Master API
  version: "1.0"
paths:
  /tasks:
    get:
      description: List all tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Task'
            type: array
      summary: List all tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task input
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/api.TaskInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Task'
      summary: Create a new task
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: Delete a task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: Task deleted
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Delete a task by ID
      tags:
      - tasks
    get:
      description: Get a task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Task'
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get a task by ID
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Update a task by ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      - description: Task input
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/api.TaskInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Task'
        "404":
          description: Task not found
          schema:
            type: string
      summary: Update a task by ID
      tags:
      - tasks
swagger: "2.0"
