// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/utsabbera/task-master/core/chat (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -package=chat . Service
//

// Package chat is a generated GoMock package.
package chat

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ProcessPrompt mocks base method.
func (m *MockService) ProcessPrompt(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPrompt", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPrompt indicates an expected call of ProcessPrompt.
func (mr *MockServiceMockRecorder) ProcessPrompt(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPrompt", reflect.TypeOf((*MockService)(nil).ProcessPrompt), arg0)
}
